### ISSUE TITLE
docker-push-to-ecr: Add support for providing a custom ECR address

### ISSUE THREAD

**Issue by stephenmathieson** [dequelabs/attest-release-scripts#34]
`auth-service` (and potentially others) will soon be deploying two Docker images to ECR (a "regular" image for us to use in production and an "on prem" image for customers). We could support this by using the `--suffix` flag (`--suffix=onprem`), but ideally we'd just have separate ECRs (`auth-service` and `auth-service-on-prem`). In order to support this here, we should create an `--ecr=` (or `--repo=`?) argument which will override the `{env}_ECR` environment variables.

**Comment by stephenmathieson** [comment]
As a stop-gap, we could just override the variables in CI:

```yaml
  deploy_onprem_docker_image:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - <<: *restore_dependency_cache
      # ...
      - run:
          name: Download and run the Docker deploy script
          command: |
            curl https://raw.githubusercontent.com/dequelabs/attest-release-scripts/develop/src/docker-push-to-ecr.sh -s -o ./docker-push-to-ecr.sh
            chmod +x ./docker-push-to-ecr.sh
            ./docker-push-to-ecr.sh
          environment:
            DEV_ECR: 111111111111.dkr.ecr.us-east-1.amazonaws.com/auth-service-on-prem
            QA_ECR: 111111111111.dkr.ecr.us-east-1.amazonaws.com/auth-service-on-prem
```
